version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    network_mode: host
    environment:
      - PUBLIC_API_URL=http://localhost/api
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src

        - action: rebuild
          path: ./frontend/package.json
          target: /app

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - DB_HOST=localhost
      - UPLOAD_FOLDER=./uploads
    volumes:
      - ./uploads:/app/uploads:z
    network_mode: host
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src

        - action: rebuild
          path: ./backend/package.json
          target: /app

  postgres:
    container_name: postgres
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: host

  caddy:
    container_name: caddy
    image: caddy
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile:z
      - caddy_data:/data
      - caddy_config:/config
      - ./uploads:/app/uploads
    network_mode: host

  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser
    restart: always
    environment:
      - FB_BASEURL=/filebrowser
    volumes:
      - ./uploads:/data:z
      - filebrowser_config:/config
    network_mode: host

volumes:
  pgdata:
  # uploads:
  caddy_data:
    external: true
  caddy_config:
  filebrowser_config:
